### PR TITLE
[app] Fix GH Action and failing tests

### LINKED ISSUE #5: [app] Set up GitHub action automations
- Code formatting
- Run tests

### LINKED ISSUE #17: [app] Add repo hook to push

### PR DESCRIPTION
**Pull request by zerefwayne**
- Update `npm test:ci` to `npm run test:ci` in angular test action.
- Fix failing tests
- Add pre push hook

### CODE REVIEW

File: diagnostics-app/src/app/app.component.ts [hunk 1]
```diff
@@ -8,20 +8,12 @@
...
 })
 export class AppComponent {
-  constructor(private updates: SwUpdate) {
-    updates.available.subscribe((event) => {
-      updates.activateUpdate().then(() => {
-        document.location.reload();
-        console.log('Updated app to latest version!');
-      });
-    });
-  }
```
Comment (zerefwayne) [inline diagnostics-app/src/app/app.component.ts:26]: These lines are responsible for refreshing the installed PWA automatically if it's updated. The `SwUpdate` is difficult to mock while testing and is not needed for now. So I have removed this feature for now.

The user can simply refresh the app and fetch updates, if any.

File: diagnostics-app/src/app/app.component.spec.ts [hunk 2]
```diff
@@ -27,11 +23,4 @@ describe('AppComponent', () => {
     const app = fixture.componentInstance;
     expect(app).toBeTruthy();
   });
-
-  it('should render title', () => {
-    const fixture = TestBed.createComponent(AppComponent);
-    fixture.detectChanges();
-    const compiled = fixture.nativeElement;
-    expect(compiled.querySelector('.content span').textContent).toContain('diagnostics-app app is running!');
-  });
```
Comment (zerefwayne) [inline diagnostics-app/src/app/app.component.spec.ts:36]: Cleanup: Unnecessary boilerplate test.

File: diagnostics-app/package.json [hunk 3]
```diff
@@ -66,6 +70,7 @@
     "@angular/compiler-cli": "~12.0.2",
     "@types/jasmine": "~3.6.0",
     "@types/node": "^12.11.1",
+    "husky": "^6.0.0",
```
Comment (Lamzin) [inline diagnostics-app/package.json]: How does it affect development workflow, do i need to do some additional steps for setup? I think I should run some commands to setup git hooks locally, can you please document it?

Comment (zerefwayne) [reply diagnostics-app/package.json]: We don't need to anything extra to set this up. I have added a `postinstall` script that initialises husky automatically!

File: diagnostics-app/package.json [hunk 4]
```diff
@@ -7,7 +7,10 @@
     "build": "ng build",
     "watch": "ng build --watch --configuration development",
     "test": "ng test",
-    "test:ci": "ng test --watch=false --browsers=ChromeHeadless --code-coverage"
+    "test:ci": "ng test --watch=false --browsers=ChromeHeadless --code-coverage",
+    "husky:prepare": "cd .. && husky install diagnostics-app/.husky",
+    "husky:prepush": "husky add .husky/pre-push \"cd diagnostics-app\nnpm run test:ci\"",
```
Comment (Lamzin) [inline diagnostics-app/package.json]: This looks a bit tricky for me. Can't we avoid using some extra package to support git hooks to make it simpler to understand what actually is running?

Also I see some duplication in github actions and here. Maybe move all logic into a script and reuse it in git hooks and github actions?

Comment (zerefwayne) [reply diagnostics-app/package.json]: Okay 👍🏻 I'll have a look at using inbuilt githooks. Maybe this logic gets simplified a lot. 

If I modify the `pre-push` hook in `.git` folder, how should I share the new file on repo so everyone can fetch it?

File: diagnostics-app/src/app/app.component.spec.ts (hunk 2 above)
Comment (MahmoudAGawad) [reply diagnostics-app/src/app/app.component.spec.ts:36]: Is it causing the build/tests to fail? If not, please do cleanup in a separate PR. Let's focus on the goal of this PR which is to fix the upload/merge Check.

File: diagnostics-app/src/app/app.component.spec.ts [hunk 5]
```diff
@@ -13,12 +13,8 @@ import { AppComponent } from './app.component';
...
   beforeEach(async () => {
     await TestBed.configureTestingModule({
-      imports: [
-        RouterTestingModule
-      ],
-      declarations: [
-        AppComponent
-      ],
+      imports: [RouterTestingModule],
+      declarations: [AppComponent],
```
Comment (MahmoudAGawad) [inline diagnostics-app/src/app/app.component.spec.ts:17]: do clean ups in a separate PR.

File: diagnostics-app/src/app/app.component.spec.ts (hunk 2 above)
Comment (zerefwayne) [reply diagnostics-app/src/app/app.component.spec.ts:36]: Yes, it causes the tests to fail.

File: diagnostics-app/src/app/app.component.spec.ts (hunk 5 above)
Comment (zerefwayne) [reply diagnostics-app/src/app/app.component.spec.ts:17]: This was done by the linter, we can keep this. Nothing's been changed here except linting.

File: diagnostics-app/src/app/app.component.ts (hunk 1 above)
Comment (MahmoudAGawad) [reply diagnostics-app/src/app/app.component.ts:26]: Ack.

File: .gitignore [hunk 6]
```diff
@@ -1,5 +1,7 @@
 # See http://help.github.com/ignore-files/ for more about ignoring files.
 
+*/.husky
+
```
Comment (MahmoudAGawad) [inline .gitignore]: remove?

File: diagnostics-app/package.json (hunk 4 above)
Comment (zerefwayne) [reply diagnostics-app/package.json]: I removed husky as a dependency and now it uses built in git hooks!

File: diagnostics-app/package.json (hunk 3 above)
Comment (zerefwayne) [reply diagnostics-app/package.json]: Not needed any more. I've documented the instructions to set up git hooks in README.md

File: README.md [hunk 7]
```diff
@@ -10,3 +10,21 @@ header:
...
+
+### Prerequisite Configuration
+
+- In the repository root, run   
+1. ```git config --unset-all core.hooksPath```
+2. ```git config --add core.hooksPath .githooks```
+
+    This will set up `.githooks` as the default directory for git hooks in this repository.
+
+- Incase git hooks don't work as intended, run this command to set necessary permissions:
```
Comment (MahmoudAGawad) [inline README.md]: nit: Incase --> In case

**Review by MahmoudAGawad — APPROVED** [review]
LGTM. Thanks!

File: .githooks/pre-push [hunk 8]
```diff
@@ -0,0 +1,6 @@
+#!/bin/sh
+
+cd diagnostics-app
+npm run test:ci
```
Comment (Lamzin) [inline .githooks/pre-push]: nit: please add `cd ..` so we always will be in the root after running some block of operations.

Comment (Lamzin) [reply .githooks/pre-push]: btw, why you don't run `npm ci` as you do it in `.github/workflows/angular.test.yml`?

Can't we just run `pre-push` script in the workflow?

Comment (zerefwayne) [reply .githooks/pre-push]: > nit: please add `cd ..` so we always will be in the root after running some block of operations.

This hook will always run from the project root automatically, so we don't need to worry about any operations.

> btw, why you don't run `npm ci` as you do it in `.github/workflows/angular.test.yml`?

That `npm ci` script is only available while an action is being executed. It is used to set up npm for testing purposes during action workflow. It is a mandatory script to be run in an npm action and has nothing to do with our app.

> Can't we just run `pre-push` script in the workflow?

We will later add on linting and style guide checks inside the pre-push workflow which are not needed in the action. All we need in the test action is the npm run test:ci command. Hence it was written that way!

Comment (Lamzin) [reply .githooks/pre-push]: > This hook will always run from the project root automatically, so we don't need to worry about any operations.

Imagine when you will add Chrome extension you will need some automation for it as well, so you will need to go back to the root directory.

So you code may look like

```
cd diagnostics-app
npm run test:ci
cd ..

cd chrome-extension
npm run test:ci
cd ..
```

The benefit of `cd ..` is that you can simply comment command for any block and script still will work.

> We will later add on linting and style guide checks inside the pre-push workflow which are not needed in the action. All we need in the test action is the npm run test:ci command.

I'd run all automation scripts including format and style check in git action as well, because git hooks are not required to run before submitting commits. Moreover, you can create PR using github web editor which does not run git hooks.


My main point is that you should have the same script for all possible checks in github actions and in git hooks.

File: .githooks/pre-push [hunk 9]
```diff
@@ -0,0 +1,6 @@
...
+
+exit 0
```
Comment (Lamzin) [inline .githooks/pre-push]: do we need it?

Comment (zerefwayne) [reply .githooks/pre-push]: No it was redundant. Removed it 👍🏻

File: .githooks/pre-push (hunk 8 above)
Comment (zerefwayne) [reply .githooks/pre-push]: > The benefit of `cd ..` is that you can simply comment command for any block and script still will work.

Oh alright! Yes this makes sense. I thought you were talking about `cd ../diagnostics-app`. 

> I'd run all automation scripts including format and style check in git action as well, because git hooks are not required to run before submitting commits. Moreover, you can create PR using github web editor which does not run git hooks.
> 
> My main point is that you should have the same script for all possible checks in github actions and in git hooks.

I missed these scenarios, will create a common npm script for this. :+1:

Comment (zerefwayne) [reply .githooks/pre-push]: @Lamzin updated the scripts!

File: .githooks/pre-push [hunk 10]
```diff
@@ -0,0 +1,5 @@
+#!/bin/sh
+
+cd diagnostics-app
+npm run script:ci
+cd ..
```
Comment (MahmoudAGawad) [inline .githooks/pre-push]: Can we do something like `npm run diagnostics-app/script:ci`?

Comment (zerefwayne) [reply .githooks/pre-push]: `npm` commands can only be executed in a folder which contains `package.json` so we have to first `cd` into the directory.

**Review by MahmoudAGawad — APPROVED** [review]
LGTM. Thanks!

**Review by Lamzin — APPROVED** [review]
LGTM, thanks!
